# This is an emmett config file.

[input.stdin]

[filter.grok]
match = { message = "%{COMBINEDAPACHELOG}" }
    
[filter.date]
match = [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]	

[output.stdout]
codec = "rubydebug"

[output.elasticsearch]
hosts = ["localhost:9200"]