# This is an emmett config file.

[[inputs]]

[inputs.generator]
count = 3
lines =  ["line 1", "line 2", "line 3"]
message = "Hello world!"
threads = 1

[inputs.http_poller]
count = 3
urls =  { test1 = "https://jsonplaceholder.typicode.com/posts/1", test2 = { method = "get", user = "AzureDiamond" } }
message = "Hello world!"
threads = 1

[[filters]]

[filters.grok]
match = { message = "%{COMBINEDAPACHELOG}" }
    
[filters.date]
match = [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]	

[[outputs]]

[outputs.stdout]
codec = "rubydebug"

[outputs.elasticsearch]
hosts = ["localhost:9200"]